packages:
  # Include all of the core configuration
  core: !include esp32-eth-bl4x4.yaml

esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    name: makstech.esp32-eth-bl4x4
    version: dev # This will be replaced by the github workflows with the `release` version

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://makstech/esp32-eth-bl4x4/esp32-eth-bl4x4.yaml@main
