# CHANGEME: Set these variable to your liking
title: ESP32-ETH-BL4x4
description: Ethernet 4x4 Button Matrix with Ethernet and Addressable LEDs, Powered by ESPHome and ESP Web Tools
theme: jekyll-theme-slate
